
CREATE TABLE PEYTO_SAMPLE 
(	
	"USER_ID" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"BIRTHDAY" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	CONSTRAINT "PEYTO_SAMPLE_PK" PRIMARY KEY ("USER_ID")
); 
